version: '3'

services:
    biblionest-front:
        image: biblionest/front:1.0.0
        build: biblionest-front
        ports:
            - ${FRONT_PORT:-80}:80
        env_file:
          - .env


    biblionest-back:
        image: biblionest/back:1.0.0
        build: biblionest-back
        ports:
            - ${BACK_PORT:-3000}:3000
        env_file:
            - .env

    db:
        image: postgres:latest
        environment:
          POSTGRES_DB: ${DB_NAME}
          POSTGRES_USER: ${DB_USER}
          POSTGRES_PASSWORD: ${DB_PASSWORD}
        ports:
            - ${DB_PORT}:5432
        env_file:
          - .env
