version: '3.7'

services:
    biblionest-front:
        image: biblionest/front:1.0.0
        build: biblionest-front
        ports:
            - ${FRONT_PORT}:4200
        command: sh -c "node_modules/.bin/ng serve --host 0.0.0.0 --port ${FRONT_PORT} --disable-host-check"
        env_file:
          - .env
        volumes:
          - ./biblionest-front:/app
          - node_modules:/app/node_modules

    biblionest-front-prod:
        image: biblionest/front-prod:1.0.0
        build: 
            context: .
            dockerfile: biblionest-front/Dockerfile.prod
        ports:
            - ${FRONT_PORT}:80
        env_file:
            - .env  
    biblionest-back:
        image: biblionest/back:1.0.0
        build: biblionest-back
        ports:
            - ${BACK_PORT:-3000}:3000
        env_file:
            - .env

    db:
        image: postgres:latest
        environment:
          POSTGRES_DB: ${PGDATABASE}
          POSTGRES_USER: ${PGUSER}
          POSTGRES_PASSWORD: ${PGPASSWORD}
          POSTGRES_HOST: ${PGHOST}
        ports:
            - ${PGPORT}:5432
        env_file:
          - .env
        volumes:
            - pg-data:/var/lib/postgresql/data
            - ./postgresql.conf:/etc/postgresql/postgresql.conf

volumes:
    pg-data:
    node_modules:
