FROM node:16.13.0-alpine as builder
WORKDIR /usr/src/app
COPY biblionest-front/package*.json ./
RUN npm install
COPY biblionest-front/. .
RUN npm run build


FROM nginx:1.19-alpine
COPY --from=0 /usr/src/app/dist/biblionest-front /usr/share/nginx/html
COPY biblionest-front/nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]